### PR TITLE
Change config for docs

### PR DESCRIPTION
**Pull request by babsey**
The PR optimize configuration for docs.

It shows warning text when using the latest version.

### CODE REVIEW

**Review by jens-br — DISMISSED** [review]
LGTM :+1:

**Review by jens-br — CHANGES_REQUESTED** [review]
Those lines look ok, but there is an import missing. Please see my PR since I cannot add comments to lines so far away from the edited lines.

**Comment by babsey** [comment]
Your PR is merged.

**Review by jens-br — APPROVED** [review]
LGTM :+1:

**Pull request merged**
