### PR TITLE
Update config for docs

### PR DESCRIPTION
**Pull request by babsey**
I sorted options to https://www.sphinx-doc.org/en/master/usage/configuration.html

### CODE REVIEW

**Review by jens-br — CHANGES_REQUESTED** [review]
This seems to break the TOC, I guess?
grafik

**Comment by babsey** [comment]
did u try to remove `_build` first?

**Comment by jens-br** [comment]
I tried that (and also did a full reload with `Strg`+`Shift`+`R`), but that did not help.

**Review by jens-br — APPROVED** [review]
I do still have the problem with the missing TOC. However, I cannot guarantee that there is still a local problem. In order to rule out that situation, we can give it a try on RTD.

**Pull request merged**
